on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check GitHub Rate Limit
        run: |
          rate_limit=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/rate_limit" | jq '.resources.core.remaining')
          while [ "$rate_limit" -le 10 ]; do
            echo "Low GitHub rate limit detected ($rate_limit remaining). Waiting for 5 minutes..."
            sleep 300
            rate_limit=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/rate_limit" | jq '.resources.core.remaining')
          done
          
      - name: WakaReadme DevMetrics
        id: devmetrics
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: 'true'
          SECTION_NAME: 'wakadev'
          BLOCKS: '=>'
          CODE_LANG: 'python'
          TIME_RANGE: 'all_time'
          LANG_COUNT: '100000'
          SHOW_TIME: 'true'
          SHOW_TOTAL: 'true'
          SHOW_MASKED_TIME: 'true'
        continue-on-error: true


      - name: Update Readme
        id: update-readme
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LINES_OF_CODE: 'True'
          SHOW_TOTAL_CODE_TIME: 'True'
          SHOW_PROFILE_VIEWS: 'True'
          SHOW_DAYS_OF_WEEK: 'True'
          SHOW_LANGUAGE: 'True'
          SHOW_OS: 'True'
          SHOW_PROJECTS: 'True'
          SHOW_TIMEZONE: 'True'
          SHOW_EDITORS: 'True'
          SHOW_LANGUAGE_PER_REPO: 'True'
          SYMBOL_VERSION: '2'
          DEBUG_LOGGING: 'True'
        continue-on-error: true

      - name: Retry if Wakatime API failed
        if: steps.update-readme.outcome == 'failure'
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LINES_OF_CODE: 'True'
          SHOW_TOTAL_CODE_TIME: 'True'
          SHOW_PROFILE_VIEWS: 'True'
          SHOW_DAYS_OF_WEEK: 'True'
          SHOW_LANGUAGE: 'True'
          SHOW_OS: 'True'
          SHOW_PROJECTS: 'True'
          SHOW_TIMEZONE: 'True'
          SHOW_EDITORS: 'True'
          SHOW_LANGUAGE_PER_REPO: 'True'
          SYMBOL_VERSION: '2'
          DEBUG_LOGGING: 'True'

      - name: Sleep for 0.6 seconds
        run: sleep 0.6
